'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class UcilistaBazaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=UcilistaBazaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Izostanocis() As DbSet(Of Izostanoci)
    Public Overridable Property Paralelkis() As DbSet(Of Paralelki)
    Public Overridable Property Uceniks() As DbSet(Of Ucenik)
    Public Overridable Property Ucilistes() As DbSet(Of Uciliste)

End Class
