'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Ucenik
    Public Property IdUcenik As Integer
    Public Property IdParalelka As Integer
    Public Property IdImeIPrezime As String
    Public Property EMBG As Nullable(Of Integer)
    Public Property SredenUspeh As Integer

End Class
